
# Spring AI - Alibaba DashScope Configuration
# ?????? DashScope API Key???????????
server:
  port: 8080

spring:
  ai:
    dashscope:
        api-key: ${QWEN_KEY}
        chat:
          options:
            model: qwen-plus

