
# Spring AI - Alibaba DashScope Configuration
# ?????? DashScope API Key???????????
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  ai:
    dashscope:
        api-key: ${QWEN_KEY}
        chat:
          options:
            model: qwen-plus

